### ISSUE TITLE
Jovo getUserId  is deprecated, use jovo.$user.getId() instead.

### ISSUE THREAD

**Issue by StErMi** [jovo-community/jovo-community-plugin-sentry#2]
Hi all, I see that in your code you are using jovo.getUserId() to get the userID.
That method has been deprecated in favor of this.$user.getId() I would recommend to change it.

Don't use jovo.$request.getUserId() because I saw that it does not work for Google Action.

**Comment by rmtuckerphx** [comment]
Fixed in v1.3.0
